### ISSUE TITLE
Annotations update TODO

### ISSUE THREAD

**Issue by Wundero** [rojo8399/PlaceholderAPI#23]
- [x] Finish JavaDocs for `PlaceholderService`
- [x] Figure out how to make tokens and other information dynamic (attach to obj not method??)
- [x] Test performance (no longer need to check expiry because I am not using loading caches)
- [x] PR for [Nucleus-Gluon](https://github.com/NucleusPowered/Gluon)
- [x] Wiki Documentation update
- [x] Remove any notation of `target` in favour of `observer`
- [x] Support for directly adding implementers of interface rather than registering methods?
- [x] Clarify that `Relational` annotation only does two things:
  - Changes method registration id to "rel_"+id
  - Allows null backfiring to trigger regular id parsing for observer (useful for message recipient based chat among other things) (Default parsing should and would likely be for source)
- Support more types for Source/Observer: (Methods specify min level requisites, will error if not provided) (I am unsure if I want to add these due to limited use cases. If use cases are suggested I will gladly add them)
  - [x] Subject ?
  - [x] MessageReceiver ?
  - [ ] Entity (or similar) ?
  - [ ] ItemStackSnapshot?
    - If I do this, I might just do data representables and/or a lower level interface of this, simply to allow support for more than just items. Might be useful, I think an opinion other than mine on this would be nice. I won't implement this yet though because I don't know any good use cases.
- Better class generation
  - [x] Don't assign local vars that are unused
  - [x] Support void method calls by returning empty string (gen class differently)
- [ ] Suggestions by people (not expecting many, if any at all, so this may be unchecked when I close this issue)
- [x] Test and deploy

Hopefully I can do most of this soon.

**Comment by Wundero** [comment]
I should note that, if I support Subject, I will completely ditch CommandSource and User as they are both implementing interfaces; I would opt for lower level interfaces that they implement, such as MessageReceiver, instead.

EDIT: The four types I would support as bases are MessageReceiver, Subject, Locatable and DataHolder. These four form the base of most informational bodies in Sponge, so that would be good. For now though I think the current system works just fine.

**Comment by Wundero** [comment]
So effectively everything useful on this has been done so I am going to close this. Just need to work on the wiki but I've been super busy so I will do it when I get more time. I will update the Wiki TODO list with exact information about what needs to be changed/added in case someone else wants to help.
